### ISSUE TITLE
bioconda recipe

### ISSUE THREAD

**Issue by mikheyev** [kdmurray91/kWIP#21]
I am trying to [write a bioconda recipe](https://github.com/MikheyevLab/bioconda-recipes/tree/kWIP) for kWIP installation. However, it fails unit tests (see below). Any idea what might be going wrong? Alternatively, do you have a recipe that you can push to bioconda?

Thanks,

Sasha

```cmake .. -DCMAKE_INSTALL_PREFIX=/opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/cc
-- Check for working C compiler: /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/c++
-- Check for working CXX compiler: /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: Not a git repository (or any of the parent directories): .git
-- Release build of kwip version: 
-- Found ZLIB: /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
-- Found Eigen3: /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/eigen3 (Required is at least version "3.0.0") 
CMake Warning (dev) at /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/share/cmake-3.9/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /opt/conda/conda-bld/kwip_1505354222916/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:75 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/build
+ make
Scanning dependencies of target libkwip
[  3%] Building CXX object src/CMakeFiles/libkwip.dir/kwip-utils.cc.o
[  6%] Building CXX object src/CMakeFiles/libkwip.dir/countmin.cc.o
[  9%] Building CXX object src/CMakeFiles/libkwip.dir/kernel.cc.o
[ 12%] Building CXX object src/CMakeFiles/libkwip.dir/population.cc.o
[ 15%] Building CXX object src/CMakeFiles/libkwip.dir/kernels/ip.cc.o
[ 18%] Building CXX object src/CMakeFiles/libkwip.dir/kernels/wip.cc.o
[ 21%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/MurmurHash3.cc.o
[ 24%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/counting.cc.o
[ 27%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/hashbits.cc.o
[ 30%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/hashtable.cc.o
[ 33%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/hllcounter.cc.o
[ 36%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/kmer_hash.cc.o
[ 39%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/labelhash.cc.o
/opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/oxli/labelhash.cc:86:1: warning: unused parameter ‘callback’ [-Wunused-parameter]
 LabelHash::consume_fasta_and_tag_with_labels(
 ^
/opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/oxli/labelhash.cc:86:1: warning: unused parameter ‘callback_data’ [-Wunused-parameter]
[ 42%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/read_aligner.cc.o
[ 45%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/read_parsers.cc.o
In file included from /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/seqan/core/include/seqan/system.h:80:0,
                 from /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/seqan/core/include/seqan/file.h:76,
                 from /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/seqan/core/include/seqan/stream.h:70,
                 from /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/seqan/core/include/seqan/seq_io.h:45,
                 from /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/oxli/read_parsers.cc:38:
/opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/seqan/core/include/seqan/system/system_sema.h:103:9: warning: unused parameter ‘init’ [-Wunused-parameter]
         Semaphore(Type init = 0):
         ^
[ 48%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/subset.cc.o
/opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/oxli/subset.cc:659:6: warning: unused parameter ‘callback_data’ [-Wunused-parameter]
 void SubsetPartition::do_partition(
      ^
/opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/src/ext/oxli/subset.cc:713:6: warning: unused parameter ‘callback_data’ [-Wunused-parameter]
 void SubsetPartition::do_partition_with_abundance(
      ^
[ 51%] Building CXX object src/CMakeFiles/libkwip.dir/ext/oxli/traversal.cc.o
[ 54%] Linking CXX static library ../lib/libkwip.a
[ 54%] Built target libkwip
Scanning dependencies of target kmerclust
[ 57%] Building CXX object src/CMakeFiles/kmerclust.dir/kmerclust/kmerclust-cli.cc.o
[ 60%] Building CXX object src/CMakeFiles/kmerclust.dir/kmerclust/js.cc.o
[ 63%] Building CXX object src/CMakeFiles/kmerclust.dir/kmerclust/d2freq.cc.o
[ 66%] Building CXX object src/CMakeFiles/kmerclust.dir/kmerclust/d2thresh.cc.o
[ 69%] Building CXX object src/CMakeFiles/kmerclust.dir/kmerclust/d2pop.cc.o
[ 72%] Linking CXX executable ../bin/kmerclust
[ 72%] Built target kmerclust
Scanning dependencies of target kwip
[ 75%] Building CXX object src/CMakeFiles/kwip.dir/kwip-cli.cc.o
[ 78%] Linking CXX executable ../bin/kwip
[ 78%] Built target kwip
Scanning dependencies of target kwip-stats
[ 81%] Building CXX object src/CMakeFiles/kwip-stats.dir/utils/entvec.cc.o
[ 84%] Linking CXX executable ../bin/kwip-stats
[ 84%] Built target kwip-stats
Scanning dependencies of target setup_tests
[ 84%] Built target setup_tests
Scanning dependencies of target test-kwip
[ 87%] Building CXX object tests/CMakeFiles/test-kwip.dir/tests.cc.o
[ 90%] Building CXX object tests/CMakeFiles/test-kwip.dir/test-lrucache.cc.o
[ 93%] Building CXX object tests/CMakeFiles/test-kwip.dir/test-kernel.cc.o
[ 96%] Building CXX object tests/CMakeFiles/test-kwip.dir/test-kwip.cc.o
[100%] Linking CXX executable ../bin/test-kwip
[100%] Built target test-kwip
+ make test
Running tests...
Test project /opt/conda/conda-bld/kwip_1505354222916/work/kWIP-0.2.0/build
    Start 1: UnitTests
1/3 Test #1: UnitTests ........................***Failed    0.00 sec
    Start 2: kWIP-cli
2/3 Test #2: kWIP-cli .........................***Failed    0.01 sec
    Start 3: old-cli
3/3 Test #3: old-cli ..........................   Passed    0.01 sec
33% tests passed, 2 tests failed out of 3
Total Test time (real) =   0.02 sec
The following tests FAILED:
	  1 - UnitTests (Failed)
	  2 - kWIP-cli (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by kdmurray91** [comment]
Hi Sasha,

Thanks very much for packaging kWIP!

Do you have commands I could use to reproduce this build locally? I'd need to run the tests interactively to check what's failing, as the specifics aren't included in that build log.

Additionally, I noticed that khmer is not a dependency of kWIP. While kWIP will build without khmer, it is not really useful without it, as you need khmer to count kmers.

Cheers,
Kevin

**Comment by mikheyev** [comment]
The commands to build are in `build.sh`. I'll include khmer as a dependency and try building again. Could this be why the unit tests are failing?

Sasha
```
#!/bin/bash

BINARY_HOME=$PREFIX/bin

cd $SRC_DIR
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=${BINARY_HOME}
make
make test
make install
```

**Comment by kdmurray91** [comment]
Actually, it might explain why the CLI tests fail. The unit tests should succeed without khmer, IIRC.

**Comment by kdmurray91** [comment]
Also, if you change `make test` to `ctest --verbose`, the full build log will be shown.

**Comment by mikheyev** [comment]
OK, that's informative. Looks like the gcc and zlib dependencies are not found. Weird, since they are included as build dependencies

```
: Test command: /bin/bash "/opt/conda/conda-bld/kwip_1505385909628/work/kWIP-0.2.0/tests/test-kmerclust-cli.sh"
3: Test timeout computed to be: 9.99988e+06
3: + bin/kmerclust ip 'data/empty-[12].ct'
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-ip-29124.err
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: + bin/kmerclust wip 'data/empty-[12].ct'
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-wip-1285.err
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: + bin/kmerclust d2pop 'data/empty-[12].ct'
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-d2pop-18992.err
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: + bin/kmerclust d2thresh 'data/empty-[12].ct'
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-d2thresh-17395.err
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: + bin/kmerclust d2freq 'data/empty-[12].ct'
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-d2freq-3852.err
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: + tee /tmp/603-6314-kmerclust-tests/empty-default-js-5213.err
3: + bin/kmerclust js 'data/empty-[12].ct'
3: bin/kmerclust: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bin/kmerclust)
3: bin/kmerclust: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bin/kmerclust)
3: + set +x
3: rm -rf /tmp/603-6314-kmerclust-tests
3/3 Test #3: old-cli ..........................   Passed    0.01 sec
```

**Comment by kdmurray91** [comment]
Hmmm, that's very odd. I just tried to reproduce this in a fresh debian stable docker container, using the exact commands you used. It worked perfectly. I'd done `apt install cmake zlib1g-dev build-essential` to install the dependencies.

Cheers,
K

**Comment by mikheyev** [comment]
This is the default environment on Travis-CI.

**Comment by mikheyev** [comment]
I posted an issue on [bioconda-recipes](https://github.com/bioconda/bioconda-recipes/issues/6027), maybe someone there has an idea.

**Comment by kdmurray91** [comment]
It's late where I am, but I suspect this is to do with cmake not detecting the dependencies correctly. The cxx/glib issues sounds like the deps are compiled with a newer abi, probably a newer os than Travis. Keep does need c++11.

I'll help debug further tomorrow if you need

Cheers, k

**Comment by kdmurray91** [comment]
Sorry, s/keep/kwip/. Damn phone

**Comment by mikheyev** [comment]
OK, we'll see if anyone on bioconda has a solution first.

**Comment by bgruening** [comment]
@mikheyev try this https://bioconda.github.io/troubleshooting.html#zlib
and do not include libgcc as build dependency.

**Comment by kdmurray91** [comment]
@mikheyev Is there anything further I can do to help w/ this? I took another look at the build log, and there's not enough there to say much. I think the main issue is that the conda-installed libraries need to be on `LD_RUN_PATH` so that the dynamic linker can find them when the tests are run. Using `make VERBOSE=1` will give me more info to work with.

**Comment by mikheyev** [comment]
OK, so adding the paths explicitly to `build.sh` did help, now there is a new problem in the UnitTests:

```
1: Test command: /anaconda/conda-bld/kwip_1506300778980/work/kWIP-0.2.0/build/bin/test-kwip
1: Test timeout computed to be: 9.99988e+06
1: dyld: Library not loaded: @rpath/libgomp.1.dylib
```

**Comment by kdmurray91** [comment]
@mikheyev Sorry, I seem to have forgotten all about this issue. Does kWIP still not build for conda?

**Comment by mikheyev** [comment]
Still no, sadly.

**Comment by phue** [comment]
Hi, is there any update on this?

**Comment by mikheyev** [comment]
Sadly, still no. My research has moved on, so it's on my list to finish largely as a way to learn how to write bioconda recipes.

**Comment by warthmann** [comment]
would definitely be a nice to have!

**Comment by phue** [comment]
> Sadly, still no. My research has moved on, so it's on my list to finish largely as a way to learn how to write bioconda recipes.

Thanks for your quick response, I think I fixed it. Bioconda now uses compiler macros, so gcc and libgcc are not required as dependencies anymore.
I tested locally and it seems to work, you can have a look here (and submit upstream if you like to, otherwise I will do it):

https://github.com/phue/bioconda-recipes/tree/kwip-recipe

Cheers,
Patrick

**Comment by phue** [comment]
I created a PR here:

https://github.com/bioconda/bioconda-recipes/pull/13127

**Comment by kdmurray91** [comment]
Thank you all very much for your work on this, and sorry I've been a bit of an absentee maintainer. I'm about to submit my thesis, which has consumed nearly all my time for the last few months.

**Comment by warthmann** [comment]
Great. Let’s tweet that kwip is now available through conda. Btw, Kevin, I hear that kwip has successfully been used to cluster DNA methylation data.

Norman

**Comment by phue** [comment]
While kWIP now builds successfully on conda, I'm running into another issue when using the bioconda package.

kWIP crashes, seemingly while calculating the false positive rate. Here is the stacktrace:

```
> Using host libthread_db library "/lib64/libthread_db.so.1".
> kwip version
> Calculating entropy weighting vector:
>   - Loading hashes into a population frequency vector:
>     - Loaded 'SRR389222_sub2.ct.gz' (2)
>     - Loaded 'SRR389222_sub1.ct.gz' (1)
>  - Finished loading hashes!
> [New Thread 0x2aaaabfa2700 (LWP 4987)]
> [New Thread 0x2aaaabda1700 (LWP 4986)]
> [New Thread 0x2aaaabba0700 (LWP 4985)]
> 
> Program received signal SIGILL, Illegal instruction.
> 0x000000000042ba47 in kwip::KernelPopulation<unsigned short>::fpr() ()
> (gdb) bt
> #0  0x000000000042ba47 in kwip::KernelPopulation<unsigned short>::fpr() ()
> #1  0x00000000004301ce in kwip::metrics::WIPKernel::calculate_entropy_vector(std::vector<std::string, std::allocator<std::string> >&) ()
> #2  0x00000000004309dd in kwip::metrics::WIPKernel::calculate_pairwise(std::vector<std::string, std::allocator<std::string> >&) ()
> #3  0x0000000000418604 in int run_pwcalc<kwip::metrics::WIPKernel>(int, char**) ()
> #4  0x00000000004163c7 in main ()
> (gdb) disas
> Dump of assembler code for function _ZN4kwip16KernelPopulationItE3fprEv:
>    0x000000000042b8f0 <+0>:     push   %rbp
>    0x000000000042b8f1 <+1>:     mov    %rsp,%rbp
>    0x000000000042b8f4 <+4>:     push   %r15
>    0x000000000042b8f6 <+6>:     push   %r14
>    0x000000000042b8f8 <+8>:     push   %r13
>    0x000000000042b8fa <+10>:    push   %r12
>    0x000000000042b8fc <+12>:    xor    %r12d,%r12d
>    0x000000000042b8ff <+15>:    push   %rbx
>    0x000000000042b900 <+16>:    mov    %rdi,%rbx
>    0x000000000042b903 <+19>:    and    $0xffffffffffffffe0,%rsp
>    0x000000000042b907 <+23>:    sub    $0x10,%rsp
>    0x000000000042b90b <+27>:    mov    0xb8(%rdi),%rax
>    0x000000000042b912 <+34>:    test   %rax,%rax
>    0x000000000042b915 <+37>:    jne    0x42b948 <_ZN4kwip16KernelPopulationItE3fprEv+88>
>    0x000000000042b917 <+39>:    vmovsd 0x3a7a1(%rip),%xmm0        # 0x4660c0
>    0x000000000042b91f <+47>:    nop
>    0x000000000042b920 <+48>:    test   %r12,%r12
>    0x000000000042b923 <+51>:    je     0x42b939 <_ZN4kwip16KernelPopulationItE3fprEv+73>
>    0x000000000042b925 <+53>:    mov    %r12,%rdi
>    0x000000000042b928 <+56>:    vmovsd %xmm0,0x8(%rsp)
>    0x000000000042b92e <+62>:    callq  0x415c40 <_ZdlPv@plt>
>    0x000000000042b933 <+67>:    vmovsd 0x8(%rsp),%xmm0
>    0x000000000042b939 <+73>:    lea    -0x28(%rbp),%rsp
>    0x000000000042b93d <+77>:    pop    %rbx
>    0x000000000042b93e <+78>:    pop    %r12
>    0x000000000042b940 <+80>:    pop    %r13
>    0x000000000042b942 <+82>:    pop    %r14
>    0x000000000042b944 <+84>:    pop    %r15
>    0x000000000042b946 <+86>:    pop    %rbp
>    0x000000000042b947 <+87>:    retq
>    0x000000000042b948 <+88>:    movabs $0x1fffffffffffffff,%rdx
>    0x000000000042b952 <+98>:    cmp    %rdx,%rax
>    0x000000000042b955 <+101>:   ja     0x42bec0 <_ZN4kwip16KernelPopulationItE3fprEv+1488>
>    0x000000000042b95b <+107>:   lea    0x0(,%rax,8),%r13
>    0x000000000042b963 <+115>:   mov    %r13,%rdi
>    0x000000000042b966 <+118>:   callq  0x415c90 <_Znwm@plt>
>    0x000000000042b96b <+123>:   xor    %esi,%esi
>    0x000000000042b96d <+125>:   mov    %r13,%rdx
>    0x000000000042b970 <+128>:   mov    %rax,%rdi
>    0x000000000042b973 <+131>:   mov    %rax,%r12
>    0x000000000042b976 <+134>:   callq  0x415a00 <memset@plt>
>    0x000000000042b97b <+139>:   mov    0xb8(%rbx),%r15
>    0x000000000042b982 <+146>:   test   %r15,%r15
>    0x000000000042b985 <+149>:   je     0x42b917 <_ZN4kwip16KernelPopulationItE3fprEv+39>
>    0x000000000042b987 <+151>:   lea    0x0(,%r15,8),%rax
>    0x000000000042b98f <+159>:   mov    0xc0(%rbx),%r14
>    0x000000000042b996 <+166>:   vmovdqa 0x3ab42(%rip),%ymm4        # 0x4664e0
>    0x000000000042b99e <+174>:   vxorpd %xmm5,%xmm5,%xmm5
>    0x000000000042b9a2 <+178>:   xor    %r10d,%r10d
>    0x000000000042b9a5 <+181>:   vpxor  %xmm3,%xmm3,%xmm3
>    0x000000000042b9a9 <+185>:   mov    %rax,0x8(%rsp)
>    0x000000000042b9ae <+190>:   mov    (%r14,%r10,1),%r8
>    0x000000000042b9b2 <+194>:   test   %r8,%r8
>    0x000000000042b9b5 <+197>:   je     0x42be28 <_ZN4kwip16KernelPopulationItE3fprEv+1336>
>    0x000000000042b9bb <+203>:   mov    0xb0(%rbx),%rax
>    0x000000000042b9c2 <+210>:   mov    %r8,%rdi
>    0x000000000042b9c5 <+213>:   mov    (%rax,%r10,1),%rsi
>    0x000000000042b9c9 <+217>:   mov    %rsi,%rax
>    0x000000000042b9cc <+220>:   and    $0x1f,%eax
>    0x000000000042b9cf <+223>:   shr    %rax
>    0x000000000042b9d2 <+226>:   neg    %rax
>    0x000000000042b9d5 <+229>:   and    $0xf,%eax
>    0x000000000042b9d8 <+232>:   cmp    %rax,%r8
>    0x000000000042b9db <+235>:   cmovbe %r8,%rax
>    0x000000000042b9df <+239>:   cmp    $0x12,%r8
>    0x000000000042b9e3 <+243>:   ja     0x42bdf0 <_ZN4kwip16KernelPopulationItE3fprEv+1280>
>    0x000000000042b9e9 <+249>:   xor    %edx,%edx
>    0x000000000042b9eb <+251>:   xor    %ecx,%ecx
>    0x000000000042b9ed <+253>:   nopl   (%rax)
>    0x000000000042b9f0 <+256>:   xor    %eax,%eax
>    0x000000000042b9f2 <+258>:   cmpw   $0x0,(%rsi,%rdx,2)
>    0x000000000042b9f7 <+263>:   setne  %al
>    0x000000000042b9fa <+266>:   add    $0x1,%rdx
>    0x000000000042b9fe <+270>:   add    %rax,%rcx
>    0x000000000042ba01 <+273>:   cmp    %rdi,%rdx
>    0x000000000042ba04 <+276>:   jne    0x42b9f0 <_ZN4kwip16KernelPopulationItE3fprEv+256>
>    0x000000000042ba06 <+278>:   cmp    %rdx,%r8
>    0x000000000042ba09 <+281>:   je     0x42bc3d <_ZN4kwip16KernelPopulationItE3fprEv+845>
>    0x000000000042ba0f <+287>:   mov    %r8,%r11
>    0x000000000042ba12 <+290>:   sub    %rdi,%r11
>    0x000000000042ba15 <+293>:   mov    %r11,%rax
>    0x000000000042ba18 <+296>:   shr    $0x4,%rax
>    0x000000000042ba1c <+300>:   mov    %rax,%r9
>    0x000000000042ba1f <+303>:   shl    $0x4,%r9
>    0x000000000042ba23 <+307>:   test   %r9,%r9
>    0x000000000042ba26 <+310>:   je     0x42bacb <_ZN4kwip16KernelPopulationItE3fprEv+475>
>    0x000000000042ba2c <+316>:   vpxor  %xmm0,%xmm0,%xmm0
>    0x000000000042ba30 <+320>:   lea    (%rsi,%rdi,2),%r13
>    0x000000000042ba34 <+324>:   xor    %edi,%edi
>    0x000000000042ba36 <+326>:   vmovdqa 0x0(%r13),%ymm1
>    0x000000000042ba3c <+332>:   add    $0x1,%rdi
>    0x000000000042ba40 <+336>:   add    $0x20,%r13
>    0x000000000042ba44 <+340>:   cmp    %rax,%rdi
> => 0x000000000042ba47 <+343>:   vpcmpeqw %ymm3,%ymm1,%ymm1
>    0x000000000042ba4b <+347>:   vpandn %ymm4,%ymm1,%ymm1
>    0x000000000042ba4f <+351>:   vpmovzxwd %xmm1,%ymm2
>    0x000000000042ba54 <+356>:   vextracti128 $0x1,%ymm1,%xmm1
>    0x000000000042ba5a <+362>:   vpmovzxdq %xmm2,%ymm6
>    0x000000000042ba5f <+367>:   vextracti128 $0x1,%ymm2,%xmm2
>    0x000000000042ba65 <+373>:   vpmovzxwd %xmm1,%ymm1
>    0x000000000042ba6a <+378>:   vpaddq %ymm0,%ymm6,%ymm0
>    0x000000000042ba6e <+382>:   vpmovzxdq %xmm2,%ymm2
>    0x000000000042ba73 <+387>:   vpaddq %ymm0,%ymm2,%ymm0
>    0x000000000042ba77 <+391>:   vpmovzxdq %xmm1,%ymm2
>    0x000000000042ba7c <+396>:   vpaddq %ymm0,%ymm2,%ymm2
>    0x000000000042ba80 <+400>:   vextracti128 $0x1,%ymm1,%xmm0
>    0x000000000042ba86 <+406>:   vpmovzxdq %xmm0,%ymm0
```

Without knowing to much about c++, I suspect it has to do with the flags used to compile it and the conda build uses cpu instructions that are not supported on the HPC environment I'm working with.

@kdmurray91 Can you share the makefile you used to generate the precompiled binaries, or do you have any other idea what might be causing it?

Cheers,
Patrick

**Comment by phue** [comment]
> Hi Patrick,
> 
> See [bioconda/bioconda-recipes#13181](https://github.com/bioconda/bioconda-recipes/pull/13181)
> 
> I hope the issue is just that I use `-march=native` by default, and that should be disabled for conda builds. Let me know if issues persist!
> 
> Cheers,
> K

Many thanks, that seems to have caused it. It's now working as expected.

**Comment by kdmurray91** [comment]
Glad to hear that!
